
DEBUG_VALUE = True

# S3
S3_ACCESS_KEY_ID = "AKIAJGEX42OGJLP7AJNA"
S3_SECRET_ACCESS_KEY = "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"
S3_BUCKET_NAME = "static.ashortstop.com"


# Foursquare
FOURSQUARE_CLIENT_ID = 'DLDABLDHR5MC2RGXXWNDVWURK2W344PGQYSHQDUIKRZ25HZM'
FOURSQUARE_CLIENT_SECRET = 'CSL1NFOWSHGFW0SG20QV52NFKQG4BK2A5ETMF2WPKOADFW1O'

# MySQL
MYSQL_DB_HOST = ""
MYSQL_DB_NAME = ""
MYSQL_DB_USER = ""
MYSQL_DB_PASSWORD = ""


# REDIS
REDIS_HOST = ""
REDIS_PORT = ""
REDIS_DB = ""


# port
WWW_PORT = 8888


WWW_COOKIE_SECRET = 'jZyJxptOS7W8VPgBJG1PR1/6rS+MjUZxhSfwSuxRZaE='
